### ISSUE TITLE
17_clue dataset link not working

### ISSUE THREAD

**Issue by OscarCreator** [t-dillon/tdoku#2]
The link to the 17 clue Sudoku puzzles do not work.
Getting 1020 error access denied.
[README](https://github.com/t-dillon/tdoku/blob/master/benchmarks/README.md)

**Comment by t-dillon** [comment]
I think this link is still correct. It's just that staffhome.ecm.uwa.edu.au is under DOS attack and Cloudflare is blocking traffic.
